name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GOPRIVATE: "github.com/paulhenri-l/*"

jobs:
  test:
    timeout-minutes: 5
    name: "Go ${{ matrix.go }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.16' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^${{ matrix.go }}'

      - name: Cache Deps
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go }}-
            ${{ runner.os }}-go-

      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: git config --global url."https://paulhenri-l:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Install deps
        run: |
          go get

      # https://marcofranssen.nl/manage-go-tools-via-go-modules/
      - name: Install tools
        run: |
          cat tools.go | grep _ | awk -F'"' '{print $2}' | xargs -t -I {} go install {}

      - name: Generate Code
        run: "go generate ./..."

      - name: Run tests
        run: "go test ./... -timeout 10s"
